---
title: "FinalProj"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
##FY2023_FMR_50_county_rev <- read_excel("Desktop/Data Sci Capstone/New Data Sources/50percrentestimates on rent/FY2023_FMR_50_county_rev.xlsx")

##CAINC5N_ALL_AREAS_2001_2023 <- read.csv("Desktop/Data Sci Capstone/New Data Sources/CAINC5N/CAINC5N__ALL_AREAS_2001_2023.csv")

##MAIRPD_MSA_2008_2023 <- read.csv("Desktop/Data Sci Capstone/New Data Sources/RPP/MAIRPD_MSA_2008_2023.csv")

##MARPI_MSA_2008_2023 <- read.csv("Desktop/Data Sci Capstone/New Data Sources/RPP/MARPI_MSA_2008_2023.csv")

##MARPP_MSA_2008_2023 <- read.csv("Desktop/Data Sci Capstone/New Data Sources/RPP/MARPP_MSA_2008_2023.csv")

##fbc_data_2024 <- read_excel("Desktop/Data Sci Capstone/New Data Sources/fbc_data_2024.xlsx", sheet = "County", skip = 1)
```

```{r}
library(dplyr)
##CAINC5N_PI <- CAINC5N_ALL_AREAS_2001_2023 %>% filter(grepl("Personal income", Description, ignore.case = TRUE))

##CAINC5N_PI <- CAINC5N_PI[order(CAINC5N_PI$GeoFIPS), ]

##CAINC5N_PI <- CAINC5N_PI %>% filter(!grepl(",", GeoName))
```

```{r}
US_News_Best_States_Rankings <- read_excel("Desktop/Data Sci Capstone/Final DS/US News Best States Rankings.xlsx")

cost_of_living_index_by_state_2025 <- read_excel("Desktop/Data Sci Capstone/Final DS/cost-of-living-index-by-state-2025.xlsx")

safest_states_in_the_us_2025 <- read_excel("Desktop/Data Sci Capstone/Final DS/safest-states-in-the-us-2025.xlsx")

SAIRPD_STATE_2008_2023 <- read.csv("Desktop/Data Sci Capstone/Final DS/RPP/SAIRPD_STATE_2008_2023.csv")

SARPI_STATE_2008_2023 <- read.csv("Desktop/Data Sci Capstone/New Data Sources/RPP/SARPI_STATE_2008_2023.csv")

SARPP_STATE_2008_2023 <- read.csv("Desktop/Data Sci Capstone/New Data Sources/RPP/SARPP_STATE_2008_2023.csv")

CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024 <- read_excel("Desktop/Data Sci Capstone/Final DS/Table11/CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024.xlsx", 
    skip = 3)

Transportation_for_America <- read_excel("Desktop/Data Sci Capstone/Final DS/Transportation for America.xlsx")
```

```{r}
rows_to_remove <- c(2206, 2207)
CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024 <- CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024[-rows_to_remove, ]

colnames(CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024)[5] <- "Violent_crime"

Total_Violent_Crimes <- CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024 %>%
  group_by(State) %>%
  summarize(TotalValueCrimes = sum(Violent_crime))
```

```{r}
rows_to_remove <- c(4, 52)
cost_of_living_index_by_state_2025 <- cost_of_living_index_by_state_2025[-rows_to_remove, ]

rows_to_remove <- c(9, 52, 53, 54, 55)
SAIRPD_STATE_2008_2023 <- SAIRPD_STATE_2008_2023[-rows_to_remove, ]

rows_to_remove <- c(209, 210, 211, 212)
SARPI_STATE_2008_2023 <- SARPI_STATE_2008_2023[-rows_to_remove, ]

rows_to_remove <- c(261, 262, 263, 264)
SARPP_STATE_2008_2023 <- SARPP_STATE_2008_2023[-rows_to_remove, ]

rows_to_remove <- c(42, 48)
Transportation_for_America <- Transportation_for_America[-rows_to_remove, ]
```

```{r}
string_to_remove <- "United States"
SARPP_STATE_2008_2023 <- SARPP_STATE_2008_2023[!grepl(string_to_remove, SARPP_STATE_2008_2023$GeoName), ]

SARPI_STATE_2008_2023 <- SARPI_STATE_2008_2023[!grepl(string_to_remove, SARPI_STATE_2008_2023$GeoName), ]

string_to_remove <- "District of Columbia"
SARPP_STATE_2008_2023 <- SARPP_STATE_2008_2023[!grepl(string_to_remove, SARPP_STATE_2008_2023$GeoName), ]

SARPI_STATE_2008_2023 <- SARPI_STATE_2008_2023[!grepl(string_to_remove, SARPI_STATE_2008_2023$GeoName), ]
```

```{r}
library(stringr)
CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024 <- CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024 %>%
      mutate(State = str_replace_all(State, "FLORIDA2", "FLORIDA"))

Total_Violent_Crimes <- Total_Violent_Crimes %>%
      mutate(State = str_replace_all(State, "FLORIDA2", "FLORIDA"))

string_to_remove <- "DISTRICT OF COLUMBIA"
CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024 <- CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024[!grepl(string_to_remove, CIUS_Table_11_Offenses_Known_to_Law_Enforcement_by_State_by_State_Tribal_and_Other_Agencies_2024$State), ]
```

```{r}
cost_of_living_index_by_state_2025 <- cost_of_living_index_by_state_2025 %>% select(-stateFlagCode)

safest_states_in_the_us_2025 <- safest_states_in_the_us_2025 %>% select(-stateFlagCode)

RPPgoods <- SARPP_STATE_2008_2023 %>%
      filter(str_detect(Description, "Goods"))

RPPhousing <- SARPP_STATE_2008_2023 %>%
      filter(str_detect(Description, "Housing"))

RPPutilities <- SARPP_STATE_2008_2023 %>%
      filter(str_detect(Description, "Utilities"))
```

```{r}
RPPgoods <- subset(RPPgoods, select = -c(TableName, IndustryClassification, Unit, X2008, X2009, X2010, X2011, X2012, X2013, X2014, X2015, X2016, X2017, X2018, X2019, X2020, X2021, X2022, LineCode))
RPPhousing <- subset(RPPhousing, select = -c(TableName, IndustryClassification, Unit, X2008, X2009, X2010, X2011, X2012, X2013, X2014, X2015, X2016, X2017, X2018, X2019, X2020, X2021, X2022, LineCode))
RPPutilities <- subset(RPPutilities, select = -c(TableName, IndustryClassification, Unit, X2008, X2009, X2010, X2011, X2012, X2013, X2014, X2015, X2016, X2017, X2018, X2019, X2020, X2021, X2022, LineCode))

columns_to_remove <- c("Transit spending per capita", "Legal restrictions on transit funding", "VMT per capita (2019)")
Transportation_for_America <- Transportation_for_America[, !(names(Transportation_for_America) %in% columns_to_remove)]
```

```{r}
RPPgoods <- RPPgoods %>%
  rename(X2023goods = X2023)

RPPhousing <- RPPhousing %>%
  rename(X2023housing = X2023)

RPPutilities <- RPPutilities %>%
  rename(X2023utilities = X2023)
```


```{r}
cost_of_living_index_by_state_2025$state <- tolower(cost_of_living_index_by_state_2025$state)
RPPgoods$state <- tolower(RPPgoods$GeoName)
RPPhousing$state <- tolower(RPPhousing$GeoName)
RPPutilities$state <- tolower(RPPutilities$GeoName)
safest_states_in_the_us_2025$state <- tolower(safest_states_in_the_us_2025$state)
Total_Violent_Crimes$state <- tolower(Total_Violent_Crimes$State)
Transportation_for_America$state <- tolower(Transportation_for_America$States)
US_News_Best_States_Rankings$state <- tolower(US_News_Best_States_Rankings$State)

```


```{r}
merged_df <- cost_of_living_index_by_state_2025 %>%
  left_join(RPPgoods, by = "state") %>%
  left_join(RPPhousing, by = "state") %>%
  left_join(RPPutilities, by = "state") %>%
  left_join(safest_states_in_the_us_2025, by = "state") %>%
  left_join(Total_Violent_Crimes, by = "state") %>%
  left_join(Transportation_for_America, by = "state") %>%
  left_join(US_News_Best_States_Rankings, by = "state")

```

```{r}
merged_df <- subset(merged_df, select = -c(State.x, State.y, GeoName, GeoFIPS, Region, GeoFIPS.x, Region.x, Description.x, Description.y, GeoFIPS.y, Region.y, Description, GeoName.x, GeoName.y, States))
```

```{r}
colnames(merged_df)[18] <- "Overall_Transportation_Score"
colnames(merged_df)[17] <- "Transit_Access_Score"
colnames(merged_df)[16] <- "VMT_Score"
colnames(merged_df)[15] <- "Legal_Restrictions_Score"
colnames(merged_df)[14] <- "Transit_Spending_Score"
colnames(merged_df)[19] <- "Overall_State_Rank"
```

```{r}
merged_df <- subset(merged_df, select = -c(CostOfLivingIndexByState_2024, CostOfLivingIndexByState_2023))
```


```{r}
mean_x <- mean(merged_df$TotalValueCrimes, na.rm = TRUE)
merged_df$TotalValueCrimes[is.na(merged_df$TotalValueCrimes)] <- mean_x
```


```{r}
colnames(merged_df)
```

```{r}
summary(merged_df)
```

```{r}
plot(merged_df$WalletHubPersonalAndResidentialSafety_2024, merged_df$WalletHubFinancialSafety_2024,
     main = "Safety Comparison", # Add a main title
     xlab = "Personal and Residential Safety",     # Label the x-axis
     ylab = "Financial Safety",     # Label the y-axis
     col = "red",              # Change point color
     pch = 19)                  # Change point shape (19 for solid circles)
```

```{r}
plot(merged_df$Overall_State_Rank, merged_df$TotalValueCrimes,
     main = "Correlation Visual between Total Crimes and Overall State Rank", # Add a main title
     xlab = "Overall Rank",     # Label the x-axis
     ylab = "Total Crimes",     # Label the y-axis
     col = "purple",              # Change point color
     pch = 19)                  # Change point shape (19 for solid circles)
```

```{r}
library(ggplot2)
ggplot(merged_df, aes(x = Overall_State_Rank, y = CostOfLivingIndexByState_2025)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE, color = "red") # Add a red linear trend line without confidence interval
```

```{r}
cor_matrix <- cor(merged_df[, -1])
print(cor_matrix)
```

```{r}
columns_to_remove <- c("state")
merged_df <- merged_df[, !(names(merged_df) %in% columns_to_remove)]
```


```{r}
library(caret)
set.seed(123) # For reproducibility
index <- createDataPartition(y = merged_df$Overall_State_Rank, p = 0.7, list = FALSE)
train_data <- merged_df[index, ]
test_data <- merged_df[-index, ]
```

```{r}
library(randomForest)
model <- randomForest(Overall_State_Rank ~ ., data = train_data)
```

```{r}
predictions <- predict(model, newdata = test_data)
```

```{r}
# Calculate Mean Absolute Error (MAE)
mae <- mean(abs(predictions - test_data$Overall_State_Rank))
print(paste("Mean Absolute Error (MAE):", round(mae, 2)))

# Calculate Root Mean Squared Error (RMSE)
rmse <- sqrt(mean((predictions - test_data$Overall_State_Rank)^2))
print(paste("Root Mean Squared Error (RMSE):", round(rmse, 2)))

# Calculate R-squared (coefficient of determination)
# Note: R-squared is often reported directly by 'summary(model)' for linear models,
# but can be calculated manually for other models.
ss_total <- sum((test_data$Overall_State_Rank - mean(test_data$Overall_State_Rank))^2)
ss_residual <- sum((test_data$Overall_State_Rank - predictions)^2)
r_squared <- 1 - (ss_residual / ss_total)
print(paste("R-squared:", round(r_squared, 2)))
```

```{r}
# Plot actual vs. predicted values
plot(test_data$Overall_State_Rank, predictions, 
     main = "Actual vs. Predicted Values",
     xlab = "Actual Values", ylab = "Predicted Values")
abline(a = 0, b = 1, col = "red", lty = 2) # Add a perfect prediction line

# Plot residuals
plot(predictions, residuals(model, newdata = test_data),
     main = "Residuals Plot",
     xlab = "Predicted Values", ylab = "Residuals")
abline(h = 0, col = "red", lty = 2)
```

